- kind: pipeline
  name: pull_request-pipeline
  platform:
    arch: amd64
    os: linux
  steps:
  - commands:
    - make build
    image: golang:1.20.4
    name: build
  - commands:
    - go test ./pkg/dronereceiver
    image: golang:1.20.4
    name: test
  trigger:
    event:
    - pull_request
  type: docker
- kind: pipeline
  name: push-pipeline
  platform:
    arch: amd64
    os: linux
  steps:
  - commands:
    - make build
    image: golang:1.20.4
    name: build
  - commands:
    - go test ./pkg/dronereceiver
    image: golang:1.20.4
    name: test
  trigger:
    branch: main
    event:
    - push
  type: docker
- kind: pipeline
  name: custom-pipeline
  platform:
    arch: amd64
    os: linux
  steps:
  - commands:
    - make build
    image: golang:1.20.4
    name: build
  - commands:
    - go test ./pkg/dronereceiver
    image: golang:1.20.4
    name: test
  trigger:
    event:
    - custom
  type: docker
- kind: pipeline
  name: verify-gen-pipeline
  platform:
    arch: amd64
    os: linux
  steps:
  - commands:
    - make metadata
    - 'if [ -n "$(git status --porcelain)" ]; then echo "ERROR: Please run make metadata
      and commit your changes." && git diff --exit-code; fi'
    image: golang:1.20.4
    name: verify-gen
  trigger:
    event:
    - pull_request
    paths:
      include:
      - pkg/dronereceiver/metadata.yaml
  type: docker
