---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang
    commands:
      - make build
  - name: test
    image: golang
    commands:
      - go test ./dronereceiver
