receivers:
# Your receivers here

processors:
  batch:
# Your processors here

connectors:
# Your connectors here

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: localhost:4317
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: "http://localhost:9090/api/v1/write"
    namespace: ci
    resource_to_telemetry_conversion:
      enabled: true
  loki:
    endpoint: http://localhost:3100/loki/api/v1/push

service:
  pipelines:
    traces:
      receivers: []
      processors: [batch]
      exporters: [otlp, debug, spanmetrics]
    logs:
      receivers: []
      processors: [batch]
      exporters: [debug, loki]
    metrics:
      receivers: [spanmetrics]
      processors: [batch]
      exporters: [debug, prometheusremotewrite]

  telemetry:
    logs:
      level: debug
