receivers:
  dronereceiver:
    collection_interval: 10s
    drone:
      token: <DRONE_TOKEN>
      host: http://localhost:8080
    endpoint: /drone/webhook
    port: 3333

processors:

exporters:
  logging:
    verbosity: detailed
  otlp:
    endpoint: localhost:4317
    tls:
      insecure: true
  prometheus:
    endpoint: 'localhost:9091'
    send_timestamps: true
    metric_expiration: 180m
    namespace: ci
    enable_open_metrics: true
    resource_to_telemetry_conversion:
      enabled: true
  prometheusremotewrite:
    endpoint: "https://prometheus-dev-01-dev-us-central-0.grafana-dev.net/api/prom/push"
    auth:
      authenticator: basicauth/client

extensions:
  basicauth/client:
    client_auth:
      username: username
      password: password

service:
  pipelines:
    traces:
      receivers: [dronereceiver]
      processors: []
      exporters: [otlp, logging]
    logs:
      receivers: [dronereceiver]
      processors: []
      exporters: [logging]
    metrics:
      receivers: [dronereceiver]
      processors: []
      exporters: [prometheusremotewrite, prometheus, logging]

  telemetry:
    logs:
      level: debug
