receivers:
  dronereceiver:
    collection_interval: 10s
    drone:
      token: <DRONE_TOKEN>
      host: <DRONE_HOST>
    endpoint: /drone/webhook
    port: 3333

processors:

exporters:
  logging:
    verbosity: detailed
  otlp:
    endpoint: localhost:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [dronereceiver]
      processors: []
      exporters: [otlp, logging]
    logs:
      receivers: [dronereceiver]
      processors: []
      exporters: [otlp, logging]
    metrics:
      receivers: [dronereceiver]
      processors: []
      exporters: [otlp, logging]

  telemetry:
    logs:
      level: debug
