receivers:
  dronereceiver:
    collection_interval: 10s
    drone:
      token: <DRONE_TOKEN>
      host: http://${NETWORK_HOST}:8080
    endpoint: /drone/webhook
    port: 3333

processors:

exporters:
  logging:
    verbosity: detailed
  otlp:
    endpoint: '${NETWORK_HOST}:4317'
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: 'http://${NETWORK_HOST}:9090/api/v1/write'
    namespace: ci
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    traces:
      receivers: [dronereceiver]
      processors: []
      exporters: [otlp, logging]
    logs:
      receivers: [dronereceiver]
      processors: []
      exporters: [logging]
    metrics:
      receivers: [dronereceiver]
      processors: []
      exporters: [prometheusremotewrite, logging]

  telemetry:
    logs:
      level: debug
