receivers:
  dronereceiver:
    collection_interval: 10s
    drone:
      token: <DRONE_TOKEN>
      host: http://localhost:8080
      database:
        host: localhost
        db: drone
        username: postgres
        password: postgres
    webhook:
      endpoint: /drone/webhook
      port: 3333
      secret: bea26a2221fd8090ea38720fc445eca6
    repos:
      grafana/grafana:
        - main
      grafana/gracie:
        - main
      grafana/grafana-ci-otel-collector:
        - main

processors:

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [30s, 1m, 5m, 10m, 30m, 1h]
    dimensions:
      - name: git.repo.name
      - name: git.branch.name
      - name: ci.drone.workflow_item.kind
      - name: ci.drone.stage.name
    exclude_dimensions:
      - service.version
      - service.name
      - span.kind
    dimensions_cache_size: 1000
    aggregation_temporality: 'AGGREGATION_TEMPORALITY_CUMULATIVE'

exporters:
  logging:
    verbosity: detailed
  otlp:
    endpoint: localhost:4317
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: 'http://localhost:9090/api/v1/write'
    namespace: ci
    resource_to_telemetry_conversion:
      enabled: true
  loki:
    endpoint: http://localhost:3100/loki/api/v1/push

service:
  pipelines:
    traces:
      receivers: [dronereceiver]
      processors: []
      exporters: [otlp, logging, spanmetrics]
    logs:
      receivers: [dronereceiver]
      processors: []
      exporters: [loki, logging]
    metrics:
      receivers: [dronereceiver, spanmetrics]
      processors: []
      exporters: [prometheusremotewrite, logging]

  telemetry:
    logs:
      level: debug
