receivers:
  dronetracereceiver:
    token: <DRONE_TOKEN>
    host: <DRONE_HOST>

processors:

exporters:
  logging:
    verbosity: detailed
  otlp:
    endpoint: localhost:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [dronetracereceiver]
      processors: []
      exporters: [otlp, logging]
    logs:
      receivers: [dronetracereceiver]
      processors: []
      exporters: [otlp, logging]
    metrics:
      receivers: [dronetracereceiver]
      processors: []
      exporters: [otlp, logging]
  telemetry:
    logs:
      level: debug
