services:
  tempo:
    image: grafana/tempo:latest@sha256:feeb085b04c07e9a63f3247969a66cf1c69137a3143ee28615765dd2e9e5562c
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # otlp grpc

  prometheus:
    image: prom/prometheus:latest@sha256:63805ebb8d2b3920190daf1cb14a60871b16fd38bed42b857a3182bc621f4996
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--web.enable-lifecycle"
      - "--web.enable-remote-write-receiver"
      - "--config.file=/etc/prometheus/prometheus.yml"

  loki:
    image: grafana/loki:latest@sha256:3165cecce301ce5b9b6e3530284b080934a05cd5cafac3d3d82edcb887b45ecd
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./config/loki.yml:/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3100/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
