module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.20

retract (
	v0.76.2
	v0.76.1
	v0.65.0
)

require github.com/open-telemetry/opentelemetry-collector-contrib/cmd/mdatagen v0.83.0
