// Code generated by mdatagen. DO NOT EDIT.

package metadata

import "go.opentelemetry.io/collector/confmap"

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms, confmap.WithErrorUnused())
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for dronereceiver metrics.
type MetricsConfig struct {
	PendingBuilds   MetricConfig `mapstructure:"pending_builds"`
	RestartedBuilds MetricConfig `mapstructure:"restarted_builds"`
	RunningBuilds   MetricConfig `mapstructure:"running_builds"`
	TotalBuilds     MetricConfig `mapstructure:"total_builds"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		PendingBuilds: MetricConfig{
			Enabled: true,
		},
		RestartedBuilds: MetricConfig{
			Enabled: true,
		},
		RunningBuilds: MetricConfig{
			Enabled: true,
		},
		TotalBuilds: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for dronereceiver metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}
