global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:

scrape_configs:
  - job_name: drone-ci
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:9091"
