// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					BuildsNumber: BuildsNumberMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []BuildsNumberMetricAttributeKey{BuildsNumberMetricAttributeKeyCiWorkflowItemStatus, BuildsNumberMetricAttributeKeyGitRepoName, BuildsNumberMetricAttributeKeyGitBranchName},
					},
					RepoInfo: RepoInfoMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []RepoInfoMetricAttributeKey{RepoInfoMetricAttributeKeyCiWorkflowItemStatus, RepoInfoMetricAttributeKeyGitRepoName, RepoInfoMetricAttributeKeyGitBranchName},
					},
					RestartsTotal: RestartsTotalMetricConfig{
						Enabled: true,
					},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					BuildsNumber: BuildsNumberMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []BuildsNumberMetricAttributeKey{BuildsNumberMetricAttributeKeyCiWorkflowItemStatus, BuildsNumberMetricAttributeKeyGitRepoName, BuildsNumberMetricAttributeKeyGitBranchName},
					},
					RepoInfo: RepoInfoMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []RepoInfoMetricAttributeKey{RepoInfoMetricAttributeKeyCiWorkflowItemStatus, RepoInfoMetricAttributeKeyGitRepoName, RepoInfoMetricAttributeKeyGitBranchName},
					},
					RestartsTotal: RestartsTotalMetricConfig{
						Enabled: false,
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(BuildsNumberMetricConfig{}, RepoInfoMetricConfig{}, RestartsTotalMetricConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}
func TestBuildsNumberMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().BuildsNumber
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []BuildsNumberMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric builds_number doesn't have an attribute invalid, valid attributes: [ci.workflow_item.status, git.repo.name, git.branch.name]")

	cfg = DefaultMetricsConfig().BuildsNumber
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestRepoInfoMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().RepoInfo
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []RepoInfoMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric repo_info doesn't have an attribute invalid, valid attributes: [ci.workflow_item.status, git.repo.name, git.branch.name]")

	cfg = DefaultMetricsConfig().RepoInfo
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}
