// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/dronereceiver component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("dronereceiver")
	ScopeName = "github.com/grafana/grafana-ci-otel-collector/receiver/dronereceiver"
)

const (
	LogsStability    = component.StabilityLevelDeprecated
	TracesStability  = component.StabilityLevelDeprecated
	MetricsStability = component.StabilityLevelDeprecated
)
