// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("githubactions")
	ScopeName = "github.com/grafana/grafana-ci-otel-collector/receiver/githubactionsreceiver"
)

const (
	TracesStability  = component.StabilityLevelAlpha
	LogsStability    = component.StabilityLevelAlpha
	MetricsStability = component.StabilityLevelAlpha
)
