// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0
			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordBuildInfoDataPoint(ts, 1, "version-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordWorkflowJobsCountDataPoint(ts, 1, "vcs.repository.name-val", "ci.github.workflow.job.labels-val", AttributeCiGithubWorkflowJobStatusCompleted, AttributeCiGithubWorkflowJobConclusionSuccess, true)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordWorkflowRunsCountDataPoint(ts, 1, "vcs.repository.name-val", "ci.github.workflow.run.labels-val", AttributeCiGithubWorkflowRunStatusCompleted, AttributeCiGithubWorkflowRunConclusionSuccess, true)

			res := pcommon.NewResource()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "build.info":
					assert.False(t, validatedMetrics["build.info"], "Found a duplicate in the metrics slice: build.info")
					validatedMetrics["build.info"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Build info.", mi.Description())
					assert.Equal(t, "{build}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					versionAttrVal, ok := dp.Attributes().Get("version")
					assert.True(t, ok)
					assert.Equal(t, "version-val", versionAttrVal.Str())
				case "workflow.jobs.count":
					assert.False(t, validatedMetrics["workflow.jobs.count"], "Found a duplicate in the metrics slice: workflow.jobs.count")
					validatedMetrics["workflow.jobs.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of jobs.", mi.Description())
					assert.Equal(t, "{job}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					vcsRepositoryNameAttrVal, ok := dp.Attributes().Get("vcs.repository.name")
					assert.True(t, ok)
					assert.Equal(t, "vcs.repository.name-val", vcsRepositoryNameAttrVal.Str())
					ciGithubWorkflowJobLabelsAttrVal, ok := dp.Attributes().Get("ci.github.workflow.job.labels")
					assert.True(t, ok)
					assert.Equal(t, "ci.github.workflow.job.labels-val", ciGithubWorkflowJobLabelsAttrVal.Str())
					ciGithubWorkflowJobStatusAttrVal, ok := dp.Attributes().Get("ci.github.workflow.job.status")
					assert.True(t, ok)
					assert.Equal(t, "completed", ciGithubWorkflowJobStatusAttrVal.Str())
					ciGithubWorkflowJobConclusionAttrVal, ok := dp.Attributes().Get("ci.github.workflow.job.conclusion")
					assert.True(t, ok)
					assert.Equal(t, "success", ciGithubWorkflowJobConclusionAttrVal.Str())
					ciGithubWorkflowJobHeadBranchIsMainAttrVal, ok := dp.Attributes().Get("ci.github.workflow.job.head_branch.is_main")
					assert.True(t, ok)
					assert.True(t, ciGithubWorkflowJobHeadBranchIsMainAttrVal.Bool())
				case "workflow.runs.count":
					assert.False(t, validatedMetrics["workflow.runs.count"], "Found a duplicate in the metrics slice: workflow.runs.count")
					validatedMetrics["workflow.runs.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of runs.", mi.Description())
					assert.Equal(t, "{run}", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					vcsRepositoryNameAttrVal, ok := dp.Attributes().Get("vcs.repository.name")
					assert.True(t, ok)
					assert.Equal(t, "vcs.repository.name-val", vcsRepositoryNameAttrVal.Str())
					ciGithubWorkflowRunLabelsAttrVal, ok := dp.Attributes().Get("ci.github.workflow.run.labels")
					assert.True(t, ok)
					assert.Equal(t, "ci.github.workflow.run.labels-val", ciGithubWorkflowRunLabelsAttrVal.Str())
					ciGithubWorkflowRunStatusAttrVal, ok := dp.Attributes().Get("ci.github.workflow.run.status")
					assert.True(t, ok)
					assert.Equal(t, "completed", ciGithubWorkflowRunStatusAttrVal.Str())
					ciGithubWorkflowRunConclusionAttrVal, ok := dp.Attributes().Get("ci.github.workflow.run.conclusion")
					assert.True(t, ok)
					assert.Equal(t, "success", ciGithubWorkflowRunConclusionAttrVal.Str())
					ciGithubWorkflowRunHeadBranchIsMainAttrVal, ok := dp.Attributes().Get("ci.github.workflow.run.head_branch.is_main")
					assert.True(t, ok)
					assert.True(t, ciGithubWorkflowRunHeadBranchIsMainAttrVal.Bool())
				}
			}
		})
	}
}
