// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
)

var (
	Type = component.MustNewType("githubactions")
)

const (
	TracesStability = component.StabilityLevelAlpha
	LogsStability   = component.StabilityLevelAlpha
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/grafana/grafana-ci-otel-collector/receiver/githubactionsreceiver")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/grafana/grafana-ci-otel-collector/receiver/githubactionsreceiver")
}
