// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					BuildInfo: BuildInfoMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []BuildInfoMetricAttributeKey{BuildInfoMetricAttributeKeyVersion},
					},
					WorkflowJobsCount: WorkflowJobsCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []WorkflowJobsCountMetricAttributeKey{WorkflowJobsCountMetricAttributeKeyVcsRepositoryName, WorkflowJobsCountMetricAttributeKeyCiGithubWorkflowJobLabels, WorkflowJobsCountMetricAttributeKeyCiGithubWorkflowJobStatus, WorkflowJobsCountMetricAttributeKeyCiGithubWorkflowJobConclusion, WorkflowJobsCountMetricAttributeKeyCiGithubWorkflowJobHeadBranchIsMain},
					},
					WorkflowRunsCount: WorkflowRunsCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []WorkflowRunsCountMetricAttributeKey{WorkflowRunsCountMetricAttributeKeyVcsRepositoryName, WorkflowRunsCountMetricAttributeKeyCiGithubWorkflowRunLabels, WorkflowRunsCountMetricAttributeKeyCiGithubWorkflowRunStatus, WorkflowRunsCountMetricAttributeKeyCiGithubWorkflowRunConclusion, WorkflowRunsCountMetricAttributeKeyCiGithubWorkflowRunHeadBranchIsMain},
					},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					BuildInfo: BuildInfoMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []BuildInfoMetricAttributeKey{BuildInfoMetricAttributeKeyVersion},
					},
					WorkflowJobsCount: WorkflowJobsCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []WorkflowJobsCountMetricAttributeKey{WorkflowJobsCountMetricAttributeKeyVcsRepositoryName, WorkflowJobsCountMetricAttributeKeyCiGithubWorkflowJobLabels, WorkflowJobsCountMetricAttributeKeyCiGithubWorkflowJobStatus, WorkflowJobsCountMetricAttributeKeyCiGithubWorkflowJobConclusion, WorkflowJobsCountMetricAttributeKeyCiGithubWorkflowJobHeadBranchIsMain},
					},
					WorkflowRunsCount: WorkflowRunsCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []WorkflowRunsCountMetricAttributeKey{WorkflowRunsCountMetricAttributeKeyVcsRepositoryName, WorkflowRunsCountMetricAttributeKeyCiGithubWorkflowRunLabels, WorkflowRunsCountMetricAttributeKeyCiGithubWorkflowRunStatus, WorkflowRunsCountMetricAttributeKeyCiGithubWorkflowRunConclusion, WorkflowRunsCountMetricAttributeKeyCiGithubWorkflowRunHeadBranchIsMain},
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(BuildInfoMetricConfig{}, WorkflowJobsCountMetricConfig{}, WorkflowRunsCountMetricConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}
